openapi: 3.0.0
info:
  title: API Utilisateurs
  version: 1.0.0
paths:
  /utilisateurs:
    get:
      summary: Liste de tous les utilisateurs
      responses:
        '200':
          description: Liste de tous les utilisateurs récupérée avec succès
  /utilisateurs/{id}:
    get:
      summary: Obtenir un utilisateur par ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: ID de l'utilisateur à obtenir
      responses:
        '200':
          description: Utilisateur récupéré avec succès
        '404':
          description: Utilisateur non trouvé
    put:
      summary: Modifier un utilisateur
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: ID de l'utilisateur à modifier
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nom:
                  type: string
                prenom:
                  type: string
              required:
                - nom
                - prenom
      responses:
        '200':
          description: Utilisateur modifié avec succès
        '400':
          description: Requête invalide
        '404':
          description: Utilisateur non trouvé
    delete:
      summary: Supprimer un utilisateur
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: ID de l'utilisateur à supprimer
      responses:
        '204':
          description: Utilisateur supprimé avec succès
        '404':
          description: Utilisateur non trouvé
  /utilisateurs/creer:
    post:
      summary: Créer un utilisateur
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nom:
                  type: string
                prenom:
                  type: string
              required:
                - nom
                - prenom
      responses:
        '201':
          description: Utilisateur créé avec succès
        '400':
          description: Requête invalide
